common: &default_settings

  license_key: '26d0ca63a20d1d9e8fa67d55fc8152afcc2110e5'

  app_name: Angry Dome

  monitor_mode: true

  developer_mode: false

  log_level: info

  browser_monitoring:
    auto_instrument: true

  audit_log:
    enabled: false

  capture_params: false

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: off
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: "ActionController::RoutingError"

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
